// copyright: Copyright (c) 2026 Lowell D. Thomas<br>
//   license: MIT (https://opensource.org/license/MIT)<br>
//
// Generated by apg-refactor, Version 1.0.0 [apg-refactor](https://github.com/ldthomas/apg-refactor)
export default function grammar() {
  // ```
  // SUMMARY
  //      rules = 91
  //       udts = 0
  //    opcodes = 363
  //        ---   ABNF original opcodes
  //        ALT = 43
  //        CAT = 48
  //        REP = 34
  //        RNM = 144
  //        TLS = 2
  //        TBS = 57
  //        TRG = 35
  //        ---   SABNF superset opcodes
  //        UDT = 0
  //        AND = 0
  //        NOT = 0
  // characters = [9 - 126]
  // ```
  /* OBJECT IDENTIFIER (magic number for internal parser use) */
  this.grammarObject = 'grammarObject';

  /* RULES */
  this.rules = [];
  this.rules[0] = { name: 'File', lower: 'file', index: 0 };
  this.rules[1] = { name: 'BlankLine', lower: 'blankline', index: 1 };
  this.rules[2] = { name: 'Rule', lower: 'rule', index: 2 };
  this.rules[3] = { name: 'RuleLookup', lower: 'rulelookup', index: 3 };
  this.rules[4] = { name: 'RuleNameTest', lower: 'rulenametest', index: 4 };
  this.rules[5] = { name: 'RuleName', lower: 'rulename', index: 5 };
  this.rules[6] = { name: 'RuleNameError', lower: 'rulenameerror', index: 6 };
  this.rules[7] = { name: 'DefinedAsTest', lower: 'definedastest', index: 7 };
  this.rules[8] = { name: 'DefinedAsError', lower: 'definedaserror', index: 8 };
  this.rules[9] = { name: 'DefinedAs', lower: 'definedas', index: 9 };
  this.rules[10] = { name: 'Defined', lower: 'defined', index: 10 };
  this.rules[11] = { name: 'IncAlt', lower: 'incalt', index: 11 };
  this.rules[12] = { name: 'RuleError', lower: 'ruleerror', index: 12 };
  this.rules[13] = { name: 'LineEndError', lower: 'lineenderror', index: 13 };
  this.rules[14] = { name: 'Alternation', lower: 'alternation', index: 14 };
  this.rules[15] = { name: 'Concatenation', lower: 'concatenation', index: 15 };
  this.rules[16] = { name: 'Repetition', lower: 'repetition', index: 16 };
  this.rules[17] = { name: 'Modifier', lower: 'modifier', index: 17 };
  this.rules[18] = { name: 'Predicate', lower: 'predicate', index: 18 };
  this.rules[19] = { name: 'BasicElement', lower: 'basicelement', index: 19 };
  this.rules[20] = { name: 'BasicElementErr', lower: 'basicelementerr', index: 20 };
  this.rules[21] = { name: 'Group', lower: 'group', index: 21 };
  this.rules[22] = { name: 'GroupError', lower: 'grouperror', index: 22 };
  this.rules[23] = { name: 'GroupOpen', lower: 'groupopen', index: 23 };
  this.rules[24] = { name: 'GroupClose', lower: 'groupclose', index: 24 };
  this.rules[25] = { name: 'Option', lower: 'option', index: 25 };
  this.rules[26] = { name: 'OptionError', lower: 'optionerror', index: 26 };
  this.rules[27] = { name: 'OptionOpen', lower: 'optionopen', index: 27 };
  this.rules[28] = { name: 'OptionClose', lower: 'optionclose', index: 28 };
  this.rules[29] = { name: 'RnmOp', lower: 'rnmop', index: 29 };
  this.rules[30] = { name: 'BkrOp', lower: 'bkrop', index: 30 };
  this.rules[31] = { name: 'bkrModifier', lower: 'bkrmodifier', index: 31 };
  this.rules[32] = { name: 'cs', lower: 'cs', index: 32 };
  this.rules[33] = { name: 'ci', lower: 'ci', index: 33 };
  this.rules[34] = { name: 'um', lower: 'um', index: 34 };
  this.rules[35] = { name: 'pm', lower: 'pm', index: 35 };
  this.rules[36] = { name: 'bkr-name', lower: 'bkr-name', index: 36 };
  this.rules[37] = { name: 'rname', lower: 'rname', index: 37 };
  this.rules[38] = { name: 'uname', lower: 'uname', index: 38 };
  this.rules[39] = { name: 'ename', lower: 'ename', index: 39 };
  this.rules[40] = { name: 'UdtOp', lower: 'udtop', index: 40 };
  this.rules[41] = { name: 'udt-non-empty', lower: 'udt-non-empty', index: 41 };
  this.rules[42] = { name: 'udt-empty', lower: 'udt-empty', index: 42 };
  this.rules[43] = { name: 'RepOp', lower: 'repop', index: 43 };
  this.rules[44] = { name: 'AltOp', lower: 'altop', index: 44 };
  this.rules[45] = { name: 'CatOp', lower: 'catop', index: 45 };
  this.rules[46] = { name: 'StarOp', lower: 'starop', index: 46 };
  this.rules[47] = { name: 'AndOp', lower: 'andop', index: 47 };
  this.rules[48] = { name: 'NotOp', lower: 'notop', index: 48 };
  this.rules[49] = { name: 'TrgOp', lower: 'trgop', index: 49 };
  this.rules[50] = { name: 'TbsOp', lower: 'tbsop', index: 50 };
  this.rules[51] = { name: 'TlsOp', lower: 'tlsop', index: 51 };
  this.rules[52] = { name: 'TlsCase', lower: 'tlscase', index: 52 };
  this.rules[53] = { name: 'TlsOpen', lower: 'tlsopen', index: 53 };
  this.rules[54] = { name: 'TlsClose', lower: 'tlsclose', index: 54 };
  this.rules[55] = { name: 'TlsString', lower: 'tlsstring', index: 55 };
  this.rules[56] = { name: 'StringTab', lower: 'stringtab', index: 56 };
  this.rules[57] = { name: 'ClsOp', lower: 'clsop', index: 57 };
  this.rules[58] = { name: 'ClsOpen', lower: 'clsopen', index: 58 };
  this.rules[59] = { name: 'ClsClose', lower: 'clsclose', index: 59 };
  this.rules[60] = { name: 'ClsString', lower: 'clsstring', index: 60 };
  this.rules[61] = { name: 'ProsVal', lower: 'prosval', index: 61 };
  this.rules[62] = { name: 'ProsValOpen', lower: 'prosvalopen', index: 62 };
  this.rules[63] = { name: 'ProsValString', lower: 'prosvalstring', index: 63 };
  this.rules[64] = { name: 'ProsValClose', lower: 'prosvalclose', index: 64 };
  this.rules[65] = { name: 'rep-min', lower: 'rep-min', index: 65 };
  this.rules[66] = { name: 'rep-min-max', lower: 'rep-min-max', index: 66 };
  this.rules[67] = { name: 'rep-max', lower: 'rep-max', index: 67 };
  this.rules[68] = { name: 'rep-num', lower: 'rep-num', index: 68 };
  this.rules[69] = { name: 'dString', lower: 'dstring', index: 69 };
  this.rules[70] = { name: 'xString', lower: 'xstring', index: 70 };
  this.rules[71] = { name: 'bString', lower: 'bstring', index: 71 };
  this.rules[72] = { name: 'Dec', lower: 'dec', index: 72 };
  this.rules[73] = { name: 'Hex', lower: 'hex', index: 73 };
  this.rules[74] = { name: 'Bin', lower: 'bin', index: 74 };
  this.rules[75] = { name: 'dmin', lower: 'dmin', index: 75 };
  this.rules[76] = { name: 'dmax', lower: 'dmax', index: 76 };
  this.rules[77] = { name: 'bmin', lower: 'bmin', index: 77 };
  this.rules[78] = { name: 'bmax', lower: 'bmax', index: 78 };
  this.rules[79] = { name: 'xmin', lower: 'xmin', index: 79 };
  this.rules[80] = { name: 'xmax', lower: 'xmax', index: 80 };
  this.rules[81] = { name: 'dnum', lower: 'dnum', index: 81 };
  this.rules[82] = { name: 'bnum', lower: 'bnum', index: 82 };
  this.rules[83] = { name: 'xnum', lower: 'xnum', index: 83 };
  this.rules[84] = { name: 'alphanum', lower: 'alphanum', index: 84 };
  this.rules[85] = { name: 'owsp', lower: 'owsp', index: 85 };
  this.rules[86] = { name: 'wsp', lower: 'wsp', index: 86 };
  this.rules[87] = { name: 'space', lower: 'space', index: 87 };
  this.rules[88] = { name: 'comment', lower: 'comment', index: 88 };
  this.rules[89] = { name: 'LineEnd', lower: 'lineend', index: 89 };
  this.rules[90] = { name: 'LineContinue', lower: 'linecontinue', index: 90 };

  /* UDTS */
  this.udts = [];

  /* OPCODES */
  /* File */
  this.rules[0].opcodes = [];
  this.rules[0].opcodes[0] = { type: 3, min: 0, max: Infinity, gl: 50, go: 18 }; // REP
  this.rules[0].opcodes[1] = { type: 1, children: [2, 3, 4], gl: 50, go: 20 }; // ALT
  this.rules[0].opcodes[2] = { type: 4, index: 1, gl: 50, go: 20 }; // RNM(BlankLine)
  this.rules[0].opcodes[3] = { type: 4, index: 2, gl: 50, go: 32 }; // RNM(Rule)
  this.rules[0].opcodes[4] = { type: 4, index: 12, gl: 50, go: 39 }; // RNM(RuleError)

  /* BlankLine */
  this.rules[1].opcodes = [];
  this.rules[1].opcodes[0] = { type: 2, children: [1, 5, 7], gl: 51, go: 18 }; // CAT
  this.rules[1].opcodes[1] = { type: 3, min: 0, max: Infinity, gl: 51, go: 18 }; // REP
  this.rules[1].opcodes[2] = { type: 1, children: [3, 4], gl: 51, go: 20 }; // ALT
  this.rules[1].opcodes[3] = { type: 6, string: [32], gl: 51, go: 20 }; // TBS
  this.rules[1].opcodes[4] = { type: 6, string: [9], gl: 51, go: 25 }; // TBS
  this.rules[1].opcodes[5] = { type: 3, min: 0, max: 1, gl: 51, go: 30 }; // REP
  this.rules[1].opcodes[6] = { type: 4, index: 88, gl: 51, go: 31 }; // RNM(comment)
  this.rules[1].opcodes[7] = { type: 4, index: 89, gl: 51, go: 40 }; // RNM(LineEnd)

  /* Rule */
  this.rules[2].opcodes = [];
  this.rules[2].opcodes[0] = { type: 2, children: [1, 2, 3, 4], gl: 52, go: 18 }; // CAT
  this.rules[2].opcodes[1] = { type: 4, index: 3, gl: 52, go: 18 }; // RNM(RuleLookup)
  this.rules[2].opcodes[2] = { type: 4, index: 85, gl: 52, go: 29 }; // RNM(owsp)
  this.rules[2].opcodes[3] = { type: 4, index: 14, gl: 52, go: 34 }; // RNM(Alternation)
  this.rules[2].opcodes[4] = { type: 1, children: [5, 8], gl: 52, go: 47 }; // ALT
  this.rules[2].opcodes[5] = { type: 2, children: [6, 7], gl: 52, go: 48 }; // CAT
  this.rules[2].opcodes[6] = { type: 4, index: 85, gl: 52, go: 48 }; // RNM(owsp)
  this.rules[2].opcodes[7] = { type: 4, index: 89, gl: 52, go: 53 }; // RNM(LineEnd)
  this.rules[2].opcodes[8] = { type: 2, children: [9, 10], gl: 53, go: 19 }; // CAT
  this.rules[2].opcodes[9] = { type: 4, index: 13, gl: 53, go: 19 }; // RNM(LineEndError)
  this.rules[2].opcodes[10] = { type: 4, index: 89, gl: 53, go: 32 }; // RNM(LineEnd)

  /* RuleLookup */
  this.rules[3].opcodes = [];
  this.rules[3].opcodes[0] = { type: 2, children: [1, 2, 3], gl: 54, go: 18 }; // CAT
  this.rules[3].opcodes[1] = { type: 4, index: 4, gl: 54, go: 18 }; // RNM(RuleNameTest)
  this.rules[3].opcodes[2] = { type: 4, index: 85, gl: 54, go: 31 }; // RNM(owsp)
  this.rules[3].opcodes[3] = { type: 4, index: 7, gl: 54, go: 36 }; // RNM(DefinedAsTest)

  /* RuleNameTest */
  this.rules[4].opcodes = [];
  this.rules[4].opcodes[0] = { type: 1, children: [1, 2], gl: 55, go: 18 }; // ALT
  this.rules[4].opcodes[1] = { type: 4, index: 5, gl: 55, go: 18 }; // RNM(RuleName)
  this.rules[4].opcodes[2] = { type: 4, index: 6, gl: 55, go: 27 }; // RNM(RuleNameError)

  /* RuleName */
  this.rules[5].opcodes = [];
  this.rules[5].opcodes[0] = { type: 4, index: 84, gl: 56, go: 18 }; // RNM(alphanum)

  /* RuleNameError */
  this.rules[6].opcodes = [];
  this.rules[6].opcodes[0] = { type: 3, min: 1, max: Infinity, gl: 57, go: 18 }; // REP
  this.rules[6].opcodes[1] = { type: 1, children: [2, 3], gl: 57, go: 21 }; // ALT
  this.rules[6].opcodes[2] = { type: 5, min: 33, max: 60, gl: 57, go: 21 }; // TRG
  this.rules[6].opcodes[3] = { type: 5, min: 62, max: 126, gl: 57, go: 29 }; // TRG

  /* DefinedAsTest */
  this.rules[7].opcodes = [];
  this.rules[7].opcodes[0] = { type: 1, children: [1, 2], gl: 58, go: 18 }; // ALT
  this.rules[7].opcodes[1] = { type: 4, index: 9, gl: 58, go: 18 }; // RNM(DefinedAs)
  this.rules[7].opcodes[2] = { type: 4, index: 8, gl: 58, go: 30 }; // RNM(DefinedAsError)

  /* DefinedAsError */
  this.rules[8].opcodes = [];
  this.rules[8].opcodes[0] = { type: 3, min: 1, max: 2, gl: 59, go: 18 }; // REP
  this.rules[8].opcodes[1] = { type: 5, min: 33, max: 126, gl: 59, go: 21 }; // TRG

  /* DefinedAs */
  this.rules[9].opcodes = [];
  this.rules[9].opcodes[0] = { type: 1, children: [1, 2], gl: 60, go: 18 }; // ALT
  this.rules[9].opcodes[1] = { type: 4, index: 11, gl: 60, go: 18 }; // RNM(IncAlt)
  this.rules[9].opcodes[2] = { type: 4, index: 10, gl: 60, go: 27 }; // RNM(Defined)

  /* Defined */
  this.rules[10].opcodes = [];
  this.rules[10].opcodes[0] = { type: 6, string: [61], gl: 61, go: 18 }; // TBS

  /* IncAlt */
  this.rules[11].opcodes = [];
  this.rules[11].opcodes[0] = { type: 6, string: [61, 47], gl: 62, go: 18 }; // TBS

  /* RuleError */
  this.rules[12].opcodes = [];
  this.rules[12].opcodes[0] = { type: 2, children: [1, 6], gl: 63, go: 18 }; // CAT
  this.rules[12].opcodes[1] = { type: 3, min: 1, max: Infinity, gl: 63, go: 18 }; // REP
  this.rules[12].opcodes[2] = { type: 1, children: [3, 4, 5], gl: 63, go: 21 }; // ALT
  this.rules[12].opcodes[3] = { type: 5, min: 32, max: 126, gl: 63, go: 21 }; // TRG
  this.rules[12].opcodes[4] = { type: 6, string: [9], gl: 63, go: 32 }; // TBS
  this.rules[12].opcodes[5] = { type: 4, index: 90, gl: 63, go: 39 }; // RNM(LineContinue)
  this.rules[12].opcodes[6] = { type: 4, index: 89, gl: 63, go: 53 }; // RNM(LineEnd)

  /* LineEndError */
  this.rules[13].opcodes = [];
  this.rules[13].opcodes[0] = { type: 3, min: 1, max: Infinity, gl: 64, go: 18 }; // REP
  this.rules[13].opcodes[1] = { type: 1, children: [2, 3, 4], gl: 64, go: 21 }; // ALT
  this.rules[13].opcodes[2] = { type: 5, min: 32, max: 126, gl: 64, go: 21 }; // TRG
  this.rules[13].opcodes[3] = { type: 6, string: [9], gl: 64, go: 32 }; // TBS
  this.rules[13].opcodes[4] = { type: 4, index: 90, gl: 64, go: 39 }; // RNM(LineContinue)

  /* Alternation */
  this.rules[14].opcodes = [];
  this.rules[14].opcodes[0] = { type: 2, children: [1, 2], gl: 65, go: 18 }; // CAT
  this.rules[14].opcodes[1] = { type: 4, index: 15, gl: 65, go: 18 }; // RNM(Concatenation)
  this.rules[14].opcodes[2] = { type: 3, min: 0, max: Infinity, gl: 65, go: 32 }; // REP
  this.rules[14].opcodes[3] = { type: 2, children: [4, 5, 6], gl: 65, go: 34 }; // CAT
  this.rules[14].opcodes[4] = { type: 4, index: 85, gl: 65, go: 34 }; // RNM(owsp)
  this.rules[14].opcodes[5] = { type: 4, index: 44, gl: 65, go: 39 }; // RNM(AltOp)
  this.rules[14].opcodes[6] = { type: 4, index: 15, gl: 65, go: 45 }; // RNM(Concatenation)

  /* Concatenation */
  this.rules[15].opcodes = [];
  this.rules[15].opcodes[0] = { type: 2, children: [1, 2], gl: 66, go: 18 }; // CAT
  this.rules[15].opcodes[1] = { type: 4, index: 16, gl: 66, go: 18 }; // RNM(Repetition)
  this.rules[15].opcodes[2] = { type: 3, min: 0, max: Infinity, gl: 66, go: 29 }; // REP
  this.rules[15].opcodes[3] = { type: 2, children: [4, 5], gl: 66, go: 31 }; // CAT
  this.rules[15].opcodes[4] = { type: 4, index: 45, gl: 66, go: 31 }; // RNM(CatOp)
  this.rules[15].opcodes[5] = { type: 4, index: 16, gl: 66, go: 37 }; // RNM(Repetition)

  /* Repetition */
  this.rules[16].opcodes = [];
  this.rules[16].opcodes[0] = { type: 2, children: [1, 3], gl: 67, go: 18 }; // CAT
  this.rules[16].opcodes[1] = { type: 3, min: 0, max: 1, gl: 67, go: 18 }; // REP
  this.rules[16].opcodes[2] = { type: 4, index: 17, gl: 67, go: 19 }; // RNM(Modifier)
  this.rules[16].opcodes[3] = { type: 1, children: [4, 5, 6, 7], gl: 67, go: 30 }; // ALT
  this.rules[16].opcodes[4] = { type: 4, index: 21, gl: 67, go: 30 }; // RNM(Group)
  this.rules[16].opcodes[5] = { type: 4, index: 25, gl: 67, go: 38 }; // RNM(Option)
  this.rules[16].opcodes[6] = { type: 4, index: 19, gl: 67, go: 47 }; // RNM(BasicElement)
  this.rules[16].opcodes[7] = { type: 4, index: 20, gl: 67, go: 62 }; // RNM(BasicElementErr)

  /* Modifier */
  this.rules[17].opcodes = [];
  this.rules[17].opcodes[0] = { type: 1, children: [1, 5], gl: 68, go: 18 }; // ALT
  this.rules[17].opcodes[1] = { type: 2, children: [2, 3], gl: 68, go: 19 }; // CAT
  this.rules[17].opcodes[2] = { type: 4, index: 18, gl: 68, go: 19 }; // RNM(Predicate)
  this.rules[17].opcodes[3] = { type: 3, min: 0, max: 1, gl: 68, go: 29 }; // REP
  this.rules[17].opcodes[4] = { type: 4, index: 43, gl: 68, go: 30 }; // RNM(RepOp)
  this.rules[17].opcodes[5] = { type: 4, index: 43, gl: 69, go: 18 }; // RNM(RepOp)

  /* Predicate */
  this.rules[18].opcodes = [];
  this.rules[18].opcodes[0] = { type: 1, children: [1, 2], gl: 70, go: 18 }; // ALT
  this.rules[18].opcodes[1] = { type: 4, index: 47, gl: 70, go: 18 }; // RNM(AndOp)
  this.rules[18].opcodes[2] = { type: 4, index: 48, gl: 70, go: 26 }; // RNM(NotOp)

  /* BasicElement */
  this.rules[19].opcodes = [];
  this.rules[19].opcodes[0] = { type: 1, children: [1, 2, 3, 4, 5, 6, 7], gl: 71, go: 18 }; // ALT
  this.rules[19].opcodes[1] = { type: 4, index: 40, gl: 71, go: 18 }; // RNM(UdtOp)
  this.rules[19].opcodes[2] = { type: 4, index: 29, gl: 72, go: 18 }; // RNM(RnmOp)
  this.rules[19].opcodes[3] = { type: 4, index: 49, gl: 73, go: 18 }; // RNM(TrgOp)
  this.rules[19].opcodes[4] = { type: 4, index: 50, gl: 74, go: 18 }; // RNM(TbsOp)
  this.rules[19].opcodes[5] = { type: 4, index: 51, gl: 75, go: 18 }; // RNM(TlsOp)
  this.rules[19].opcodes[6] = { type: 4, index: 57, gl: 76, go: 18 }; // RNM(ClsOp)
  this.rules[19].opcodes[7] = { type: 4, index: 61, gl: 77, go: 18 }; // RNM(ProsVal)

  /* BasicElementErr */
  this.rules[20].opcodes = [];
  this.rules[20].opcodes[0] = { type: 3, min: 1, max: Infinity, gl: 78, go: 18 }; // REP
  this.rules[20].opcodes[1] = { type: 1, children: [2, 3, 4, 5], gl: 78, go: 21 }; // ALT
  this.rules[20].opcodes[2] = { type: 5, min: 33, max: 40, gl: 78, go: 21 }; // TRG
  this.rules[20].opcodes[3] = { type: 5, min: 42, max: 46, gl: 78, go: 29 }; // TRG
  this.rules[20].opcodes[4] = { type: 5, min: 48, max: 92, gl: 78, go: 37 }; // TRG
  this.rules[20].opcodes[5] = { type: 5, min: 94, max: 126, gl: 78, go: 45 }; // TRG

  /* Group */
  this.rules[21].opcodes = [];
  this.rules[21].opcodes[0] = { type: 2, children: [1, 2, 3], gl: 79, go: 18 }; // CAT
  this.rules[21].opcodes[1] = { type: 4, index: 23, gl: 79, go: 18 }; // RNM(GroupOpen)
  this.rules[21].opcodes[2] = { type: 4, index: 14, gl: 79, go: 29 }; // RNM(Alternation)
  this.rules[21].opcodes[3] = { type: 1, children: [4, 5], gl: 79, go: 42 }; // ALT
  this.rules[21].opcodes[4] = { type: 4, index: 24, gl: 79, go: 42 }; // RNM(GroupClose)
  this.rules[21].opcodes[5] = { type: 4, index: 22, gl: 79, go: 55 }; // RNM(GroupError)

  /* GroupError */
  this.rules[22].opcodes = [];
  this.rules[22].opcodes[0] = { type: 3, min: 1, max: Infinity, gl: 80, go: 18 }; // REP
  this.rules[22].opcodes[1] = { type: 1, children: [2, 3, 4, 5], gl: 80, go: 21 }; // ALT
  this.rules[22].opcodes[2] = { type: 5, min: 33, max: 40, gl: 80, go: 21 }; // TRG
  this.rules[22].opcodes[3] = { type: 5, min: 42, max: 46, gl: 80, go: 29 }; // TRG
  this.rules[22].opcodes[4] = { type: 5, min: 48, max: 92, gl: 80, go: 37 }; // TRG
  this.rules[22].opcodes[5] = { type: 5, min: 94, max: 126, gl: 80, go: 45 }; // TRG

  /* GroupOpen */
  this.rules[23].opcodes = [];
  this.rules[23].opcodes[0] = { type: 2, children: [1, 2], gl: 81, go: 18 }; // CAT
  this.rules[23].opcodes[1] = { type: 6, string: [40], gl: 81, go: 18 }; // TBS
  this.rules[23].opcodes[2] = { type: 4, index: 85, gl: 81, go: 23 }; // RNM(owsp)

  /* GroupClose */
  this.rules[24].opcodes = [];
  this.rules[24].opcodes[0] = { type: 2, children: [1, 2], gl: 82, go: 18 }; // CAT
  this.rules[24].opcodes[1] = { type: 4, index: 85, gl: 82, go: 18 }; // RNM(owsp)
  this.rules[24].opcodes[2] = { type: 6, string: [41], gl: 82, go: 23 }; // TBS

  /* Option */
  this.rules[25].opcodes = [];
  this.rules[25].opcodes[0] = { type: 2, children: [1, 2, 3], gl: 83, go: 18 }; // CAT
  this.rules[25].opcodes[1] = { type: 4, index: 27, gl: 83, go: 18 }; // RNM(OptionOpen)
  this.rules[25].opcodes[2] = { type: 4, index: 14, gl: 83, go: 29 }; // RNM(Alternation)
  this.rules[25].opcodes[3] = { type: 1, children: [4, 5], gl: 83, go: 42 }; // ALT
  this.rules[25].opcodes[4] = { type: 4, index: 28, gl: 83, go: 42 }; // RNM(OptionClose)
  this.rules[25].opcodes[5] = { type: 4, index: 26, gl: 83, go: 56 }; // RNM(OptionError)

  /* OptionError */
  this.rules[26].opcodes = [];
  this.rules[26].opcodes[0] = { type: 3, min: 1, max: Infinity, gl: 84, go: 18 }; // REP
  this.rules[26].opcodes[1] = { type: 1, children: [2, 3, 4, 5], gl: 84, go: 21 }; // ALT
  this.rules[26].opcodes[2] = { type: 5, min: 33, max: 40, gl: 84, go: 21 }; // TRG
  this.rules[26].opcodes[3] = { type: 5, min: 42, max: 46, gl: 84, go: 29 }; // TRG
  this.rules[26].opcodes[4] = { type: 5, min: 48, max: 92, gl: 84, go: 37 }; // TRG
  this.rules[26].opcodes[5] = { type: 5, min: 94, max: 126, gl: 84, go: 45 }; // TRG

  /* OptionOpen */
  this.rules[27].opcodes = [];
  this.rules[27].opcodes[0] = { type: 2, children: [1, 2], gl: 85, go: 18 }; // CAT
  this.rules[27].opcodes[1] = { type: 6, string: [91], gl: 85, go: 18 }; // TBS
  this.rules[27].opcodes[2] = { type: 4, index: 85, gl: 85, go: 23 }; // RNM(owsp)

  /* OptionClose */
  this.rules[28].opcodes = [];
  this.rules[28].opcodes[0] = { type: 2, children: [1, 2], gl: 86, go: 18 }; // CAT
  this.rules[28].opcodes[1] = { type: 4, index: 85, gl: 86, go: 18 }; // RNM(owsp)
  this.rules[28].opcodes[2] = { type: 6, string: [93], gl: 86, go: 23 }; // TBS

  /* RnmOp */
  this.rules[29].opcodes = [];
  this.rules[29].opcodes[0] = { type: 4, index: 84, gl: 87, go: 18 }; // RNM(alphanum)

  /* BkrOp */
  this.rules[30].opcodes = [];
  this.rules[30].opcodes[0] = { type: 2, children: [1, 2, 4], gl: 88, go: 18 }; // CAT
  this.rules[30].opcodes[1] = { type: 6, string: [92], gl: 88, go: 18 }; // TBS
  this.rules[30].opcodes[2] = { type: 3, min: 0, max: 1, gl: 88, go: 23 }; // REP
  this.rules[30].opcodes[3] = { type: 4, index: 31, gl: 88, go: 24 }; // RNM(bkrModifier)
  this.rules[30].opcodes[4] = { type: 4, index: 36, gl: 88, go: 37 }; // RNM(bkr-name)

  /* bkrModifier */
  this.rules[31].opcodes = [];
  this.rules[31].opcodes[0] = { type: 1, children: [1, 7, 13, 19], gl: 89, go: 18 }; // ALT
  this.rules[31].opcodes[1] = { type: 2, children: [2, 3], gl: 89, go: 19 }; // CAT
  this.rules[31].opcodes[2] = { type: 4, index: 32, gl: 89, go: 19 }; // RNM(cs)
  this.rules[31].opcodes[3] = { type: 3, min: 0, max: 1, gl: 89, go: 22 }; // REP
  this.rules[31].opcodes[4] = { type: 1, children: [5, 6], gl: 89, go: 23 }; // ALT
  this.rules[31].opcodes[5] = { type: 4, index: 34, gl: 89, go: 23 }; // RNM(um)
  this.rules[31].opcodes[6] = { type: 4, index: 35, gl: 89, go: 28 }; // RNM(pm)
  this.rules[31].opcodes[7] = { type: 2, children: [8, 9], gl: 89, go: 36 }; // CAT
  this.rules[31].opcodes[8] = { type: 4, index: 33, gl: 89, go: 36 }; // RNM(ci)
  this.rules[31].opcodes[9] = { type: 3, min: 0, max: 1, gl: 89, go: 39 }; // REP
  this.rules[31].opcodes[10] = { type: 1, children: [11, 12], gl: 89, go: 40 }; // ALT
  this.rules[31].opcodes[11] = { type: 4, index: 34, gl: 89, go: 40 }; // RNM(um)
  this.rules[31].opcodes[12] = { type: 4, index: 35, gl: 89, go: 45 }; // RNM(pm)
  this.rules[31].opcodes[13] = { type: 2, children: [14, 15], gl: 89, go: 53 }; // CAT
  this.rules[31].opcodes[14] = { type: 4, index: 34, gl: 89, go: 53 }; // RNM(um)
  this.rules[31].opcodes[15] = { type: 3, min: 0, max: 1, gl: 89, go: 56 }; // REP
  this.rules[31].opcodes[16] = { type: 1, children: [17, 18], gl: 89, go: 57 }; // ALT
  this.rules[31].opcodes[17] = { type: 4, index: 32, gl: 89, go: 57 }; // RNM(cs)
  this.rules[31].opcodes[18] = { type: 4, index: 33, gl: 89, go: 61 }; // RNM(ci)
  this.rules[31].opcodes[19] = { type: 2, children: [20, 21], gl: 89, go: 69 }; // CAT
  this.rules[31].opcodes[20] = { type: 4, index: 35, gl: 89, go: 69 }; // RNM(pm)
  this.rules[31].opcodes[21] = { type: 3, min: 0, max: 1, gl: 89, go: 72 }; // REP
  this.rules[31].opcodes[22] = { type: 1, children: [23, 24], gl: 89, go: 73 }; // ALT
  this.rules[31].opcodes[23] = { type: 4, index: 32, gl: 89, go: 73 }; // RNM(cs)
  this.rules[31].opcodes[24] = { type: 4, index: 33, gl: 89, go: 78 }; // RNM(ci)

  /* cs */
  this.rules[32].opcodes = [];
  this.rules[32].opcodes[0] = { type: 6, string: [37, 115], gl: 90, go: 18 }; // TBS

  /* ci */
  this.rules[33].opcodes = [];
  this.rules[33].opcodes[0] = { type: 6, string: [37, 105], gl: 91, go: 18 }; // TBS

  /* um */
  this.rules[34].opcodes = [];
  this.rules[34].opcodes[0] = { type: 6, string: [37, 117], gl: 92, go: 18 }; // TBS

  /* pm */
  this.rules[35].opcodes = [];
  this.rules[35].opcodes[0] = { type: 6, string: [37, 112], gl: 93, go: 18 }; // TBS

  /* bkr-name */
  this.rules[36].opcodes = [];
  this.rules[36].opcodes[0] = { type: 1, children: [1, 2, 3], gl: 94, go: 18 }; // ALT
  this.rules[36].opcodes[1] = { type: 4, index: 38, gl: 94, go: 18 }; // RNM(uname)
  this.rules[36].opcodes[2] = { type: 4, index: 39, gl: 94, go: 26 }; // RNM(ename)
  this.rules[36].opcodes[3] = { type: 4, index: 37, gl: 94, go: 34 }; // RNM(rname)

  /* rname */
  this.rules[37].opcodes = [];
  this.rules[37].opcodes[0] = { type: 4, index: 84, gl: 95, go: 18 }; // RNM(alphanum)

  /* uname */
  this.rules[38].opcodes = [];
  this.rules[38].opcodes[0] = { type: 2, children: [1, 2], gl: 96, go: 18 }; // CAT
  this.rules[38].opcodes[1] = { type: 6, string: [117, 95], gl: 96, go: 18 }; // TBS
  this.rules[38].opcodes[2] = { type: 4, index: 84, gl: 96, go: 27 }; // RNM(alphanum)

  /* ename */
  this.rules[39].opcodes = [];
  this.rules[39].opcodes[0] = { type: 2, children: [1, 2], gl: 97, go: 18 }; // CAT
  this.rules[39].opcodes[1] = { type: 6, string: [101, 95], gl: 97, go: 18 }; // TBS
  this.rules[39].opcodes[2] = { type: 4, index: 84, gl: 97, go: 27 }; // RNM(alphanum)

  /* UdtOp */
  this.rules[40].opcodes = [];
  this.rules[40].opcodes[0] = { type: 1, children: [1, 2], gl: 98, go: 18 }; // ALT
  this.rules[40].opcodes[1] = { type: 4, index: 42, gl: 98, go: 18 }; // RNM(udt-empty)
  this.rules[40].opcodes[2] = { type: 4, index: 41, gl: 99, go: 18 }; // RNM(udt-non-empty)

  /* udt-non-empty */
  this.rules[41].opcodes = [];
  this.rules[41].opcodes[0] = { type: 2, children: [1, 2], gl: 100, go: 18 }; // CAT
  this.rules[41].opcodes[1] = { type: 6, string: [117, 95], gl: 100, go: 18 }; // TBS
  this.rules[41].opcodes[2] = { type: 4, index: 84, gl: 100, go: 27 }; // RNM(alphanum)

  /* udt-empty */
  this.rules[42].opcodes = [];
  this.rules[42].opcodes[0] = { type: 2, children: [1, 2], gl: 101, go: 18 }; // CAT
  this.rules[42].opcodes[1] = { type: 6, string: [101, 95], gl: 101, go: 18 }; // TBS
  this.rules[42].opcodes[2] = { type: 4, index: 84, gl: 101, go: 27 }; // RNM(alphanum)

  /* RepOp */
  this.rules[43].opcodes = [];
  this.rules[43].opcodes[0] = { type: 1, children: [1, 5, 8, 11, 12], gl: 102, go: 18 }; // ALT
  this.rules[43].opcodes[1] = { type: 2, children: [2, 3, 4], gl: 102, go: 19 }; // CAT
  this.rules[43].opcodes[2] = { type: 4, index: 65, gl: 102, go: 19 }; // RNM(rep-min)
  this.rules[43].opcodes[3] = { type: 4, index: 46, gl: 102, go: 27 }; // RNM(StarOp)
  this.rules[43].opcodes[4] = { type: 4, index: 67, gl: 102, go: 34 }; // RNM(rep-max)
  this.rules[43].opcodes[5] = { type: 2, children: [6, 7], gl: 103, go: 19 }; // CAT
  this.rules[43].opcodes[6] = { type: 4, index: 65, gl: 103, go: 19 }; // RNM(rep-min)
  this.rules[43].opcodes[7] = { type: 4, index: 46, gl: 103, go: 27 }; // RNM(StarOp)
  this.rules[43].opcodes[8] = { type: 2, children: [9, 10], gl: 104, go: 19 }; // CAT
  this.rules[43].opcodes[9] = { type: 4, index: 46, gl: 104, go: 19 }; // RNM(StarOp)
  this.rules[43].opcodes[10] = { type: 4, index: 67, gl: 104, go: 26 }; // RNM(rep-max)
  this.rules[43].opcodes[11] = { type: 4, index: 46, gl: 105, go: 18 }; // RNM(StarOp)
  this.rules[43].opcodes[12] = { type: 4, index: 66, gl: 106, go: 18 }; // RNM(rep-min-max)

  /* AltOp */
  this.rules[44].opcodes = [];
  this.rules[44].opcodes[0] = { type: 2, children: [1, 2], gl: 107, go: 18 }; // CAT
  this.rules[44].opcodes[1] = { type: 6, string: [47], gl: 107, go: 18 }; // TBS
  this.rules[44].opcodes[2] = { type: 4, index: 85, gl: 107, go: 23 }; // RNM(owsp)

  /* CatOp */
  this.rules[45].opcodes = [];
  this.rules[45].opcodes[0] = { type: 4, index: 86, gl: 108, go: 18 }; // RNM(wsp)

  /* StarOp */
  this.rules[46].opcodes = [];
  this.rules[46].opcodes[0] = { type: 6, string: [42], gl: 109, go: 18 }; // TBS

  /* AndOp */
  this.rules[47].opcodes = [];
  this.rules[47].opcodes[0] = { type: 6, string: [38], gl: 110, go: 18 }; // TBS

  /* NotOp */
  this.rules[48].opcodes = [];
  this.rules[48].opcodes[0] = { type: 6, string: [33], gl: 111, go: 18 }; // TBS

  /* TrgOp */
  this.rules[49].opcodes = [];
  this.rules[49].opcodes[0] = { type: 2, children: [1, 2], gl: 112, go: 18 }; // CAT
  this.rules[49].opcodes[1] = { type: 6, string: [37], gl: 112, go: 18 }; // TBS
  this.rules[49].opcodes[2] = { type: 1, children: [3, 8, 13], gl: 112, go: 24 }; // ALT
  this.rules[49].opcodes[3] = { type: 2, children: [4, 5, 6, 7], gl: 112, go: 25 }; // CAT
  this.rules[49].opcodes[4] = { type: 4, index: 72, gl: 112, go: 25 }; // RNM(Dec)
  this.rules[49].opcodes[5] = { type: 4, index: 75, gl: 112, go: 29 }; // RNM(dmin)
  this.rules[49].opcodes[6] = { type: 6, string: [45], gl: 112, go: 34 }; // TBS
  this.rules[49].opcodes[7] = { type: 4, index: 76, gl: 112, go: 39 }; // RNM(dmax)
  this.rules[49].opcodes[8] = { type: 2, children: [9, 10, 11, 12], gl: 112, go: 48 }; // CAT
  this.rules[49].opcodes[9] = { type: 4, index: 73, gl: 112, go: 48 }; // RNM(Hex)
  this.rules[49].opcodes[10] = { type: 4, index: 79, gl: 112, go: 52 }; // RNM(xmin)
  this.rules[49].opcodes[11] = { type: 6, string: [45], gl: 112, go: 57 }; // TBS
  this.rules[49].opcodes[12] = { type: 4, index: 80, gl: 112, go: 62 }; // RNM(xmax)
  this.rules[49].opcodes[13] = { type: 2, children: [14, 15, 16, 17], gl: 112, go: 71 }; // CAT
  this.rules[49].opcodes[14] = { type: 4, index: 74, gl: 112, go: 71 }; // RNM(Bin)
  this.rules[49].opcodes[15] = { type: 4, index: 77, gl: 112, go: 75 }; // RNM(bmin)
  this.rules[49].opcodes[16] = { type: 6, string: [45], gl: 112, go: 80 }; // TBS
  this.rules[49].opcodes[17] = { type: 4, index: 78, gl: 112, go: 85 }; // RNM(bmax)

  /* TbsOp */
  this.rules[50].opcodes = [];
  this.rules[50].opcodes[0] = { type: 2, children: [1, 2], gl: 113, go: 18 }; // CAT
  this.rules[50].opcodes[1] = { type: 6, string: [37], gl: 113, go: 18 }; // TBS
  this.rules[50].opcodes[2] = { type: 1, children: [3, 10, 17], gl: 113, go: 24 }; // ALT
  this.rules[50].opcodes[3] = { type: 2, children: [4, 5, 6], gl: 113, go: 25 }; // CAT
  this.rules[50].opcodes[4] = { type: 4, index: 72, gl: 113, go: 25 }; // RNM(Dec)
  this.rules[50].opcodes[5] = { type: 4, index: 69, gl: 113, go: 29 }; // RNM(dString)
  this.rules[50].opcodes[6] = { type: 3, min: 0, max: Infinity, gl: 113, go: 37 }; // REP
  this.rules[50].opcodes[7] = { type: 2, children: [8, 9], gl: 113, go: 39 }; // CAT
  this.rules[50].opcodes[8] = { type: 6, string: [46], gl: 113, go: 39 }; // TBS
  this.rules[50].opcodes[9] = { type: 4, index: 69, gl: 113, go: 44 }; // RNM(dString)
  this.rules[50].opcodes[10] = { type: 2, children: [11, 12, 13], gl: 113, go: 57 }; // CAT
  this.rules[50].opcodes[11] = { type: 4, index: 73, gl: 113, go: 57 }; // RNM(Hex)
  this.rules[50].opcodes[12] = { type: 4, index: 70, gl: 113, go: 61 }; // RNM(xString)
  this.rules[50].opcodes[13] = { type: 3, min: 0, max: Infinity, gl: 113, go: 69 }; // REP
  this.rules[50].opcodes[14] = { type: 2, children: [15, 16], gl: 113, go: 71 }; // CAT
  this.rules[50].opcodes[15] = { type: 6, string: [46], gl: 113, go: 71 }; // TBS
  this.rules[50].opcodes[16] = { type: 4, index: 70, gl: 113, go: 76 }; // RNM(xString)
  this.rules[50].opcodes[17] = { type: 2, children: [18, 19, 20], gl: 113, go: 89 }; // CAT
  this.rules[50].opcodes[18] = { type: 4, index: 74, gl: 113, go: 89 }; // RNM(Bin)
  this.rules[50].opcodes[19] = { type: 4, index: 71, gl: 113, go: 93 }; // RNM(bString)
  this.rules[50].opcodes[20] = { type: 3, min: 0, max: Infinity, gl: 113, go: 101 }; // REP
  this.rules[50].opcodes[21] = { type: 2, children: [22, 23], gl: 113, go: 103 }; // CAT
  this.rules[50].opcodes[22] = { type: 6, string: [46], gl: 113, go: 103 }; // TBS
  this.rules[50].opcodes[23] = { type: 4, index: 71, gl: 113, go: 108 }; // RNM(bString)

  /* TlsOp */
  this.rules[51].opcodes = [];
  this.rules[51].opcodes[0] = { type: 2, children: [1, 2, 3, 4], gl: 114, go: 18 }; // CAT
  this.rules[51].opcodes[1] = { type: 4, index: 52, gl: 114, go: 18 }; // RNM(TlsCase)
  this.rules[51].opcodes[2] = { type: 4, index: 53, gl: 114, go: 26 }; // RNM(TlsOpen)
  this.rules[51].opcodes[3] = { type: 4, index: 55, gl: 114, go: 34 }; // RNM(TlsString)
  this.rules[51].opcodes[4] = { type: 4, index: 54, gl: 114, go: 44 }; // RNM(TlsClose)

  /* TlsCase */
  this.rules[52].opcodes = [];
  this.rules[52].opcodes[0] = { type: 3, min: 0, max: 1, gl: 115, go: 18 }; // REP
  this.rules[52].opcodes[1] = { type: 1, children: [2, 3], gl: 115, go: 19 }; // ALT
  this.rules[52].opcodes[2] = { type: 7, string: [37, 105], gl: 115, go: 19 }; // TLS
  this.rules[52].opcodes[3] = { type: 7, string: [37, 115], gl: 115, go: 26 }; // TLS

  /* TlsOpen */
  this.rules[53].opcodes = [];
  this.rules[53].opcodes[0] = { type: 6, string: [34], gl: 116, go: 18 }; // TBS

  /* TlsClose */
  this.rules[54].opcodes = [];
  this.rules[54].opcodes[0] = { type: 6, string: [34], gl: 117, go: 18 }; // TBS

  /* TlsString */
  this.rules[55].opcodes = [];
  this.rules[55].opcodes[0] = { type: 3, min: 0, max: Infinity, gl: 118, go: 18 }; // REP
  this.rules[55].opcodes[1] = { type: 1, children: [2, 3, 4], gl: 118, go: 20 }; // ALT
  this.rules[55].opcodes[2] = { type: 5, min: 32, max: 33, gl: 118, go: 20 }; // TRG
  this.rules[55].opcodes[3] = { type: 5, min: 35, max: 126, gl: 118, go: 28 }; // TRG
  this.rules[55].opcodes[4] = { type: 4, index: 56, gl: 118, go: 37 }; // RNM(StringTab)

  /* StringTab */
  this.rules[56].opcodes = [];
  this.rules[56].opcodes[0] = { type: 6, string: [9], gl: 119, go: 18 }; // TBS

  /* ClsOp */
  this.rules[57].opcodes = [];
  this.rules[57].opcodes[0] = { type: 2, children: [1, 2, 3], gl: 120, go: 18 }; // CAT
  this.rules[57].opcodes[1] = { type: 4, index: 58, gl: 120, go: 18 }; // RNM(ClsOpen)
  this.rules[57].opcodes[2] = { type: 4, index: 60, gl: 120, go: 26 }; // RNM(ClsString)
  this.rules[57].opcodes[3] = { type: 4, index: 59, gl: 120, go: 36 }; // RNM(ClsClose)

  /* ClsOpen */
  this.rules[58].opcodes = [];
  this.rules[58].opcodes[0] = { type: 6, string: [39], gl: 121, go: 18 }; // TBS

  /* ClsClose */
  this.rules[59].opcodes = [];
  this.rules[59].opcodes[0] = { type: 6, string: [39], gl: 122, go: 18 }; // TBS

  /* ClsString */
  this.rules[60].opcodes = [];
  this.rules[60].opcodes[0] = { type: 3, min: 0, max: Infinity, gl: 123, go: 18 }; // REP
  this.rules[60].opcodes[1] = { type: 1, children: [2, 3, 4], gl: 123, go: 20 }; // ALT
  this.rules[60].opcodes[2] = { type: 5, min: 32, max: 38, gl: 123, go: 20 }; // TRG
  this.rules[60].opcodes[3] = { type: 5, min: 40, max: 126, gl: 123, go: 28 }; // TRG
  this.rules[60].opcodes[4] = { type: 4, index: 56, gl: 123, go: 37 }; // RNM(StringTab)

  /* ProsVal */
  this.rules[61].opcodes = [];
  this.rules[61].opcodes[0] = { type: 2, children: [1, 2, 3], gl: 124, go: 18 }; // CAT
  this.rules[61].opcodes[1] = { type: 4, index: 62, gl: 124, go: 18 }; // RNM(ProsValOpen)
  this.rules[61].opcodes[2] = { type: 4, index: 63, gl: 124, go: 30 }; // RNM(ProsValString)
  this.rules[61].opcodes[3] = { type: 4, index: 64, gl: 124, go: 44 }; // RNM(ProsValClose)

  /* ProsValOpen */
  this.rules[62].opcodes = [];
  this.rules[62].opcodes[0] = { type: 6, string: [60], gl: 125, go: 18 }; // TBS

  /* ProsValString */
  this.rules[63].opcodes = [];
  this.rules[63].opcodes[0] = { type: 3, min: 0, max: Infinity, gl: 126, go: 18 }; // REP
  this.rules[63].opcodes[1] = { type: 1, children: [2, 3, 4], gl: 126, go: 20 }; // ALT
  this.rules[63].opcodes[2] = { type: 5, min: 32, max: 61, gl: 126, go: 20 }; // TRG
  this.rules[63].opcodes[3] = { type: 5, min: 63, max: 126, gl: 126, go: 28 }; // TRG
  this.rules[63].opcodes[4] = { type: 4, index: 56, gl: 126, go: 37 }; // RNM(StringTab)

  /* ProsValClose */
  this.rules[64].opcodes = [];
  this.rules[64].opcodes[0] = { type: 6, string: [62], gl: 127, go: 18 }; // TBS

  /* rep-min */
  this.rules[65].opcodes = [];
  this.rules[65].opcodes[0] = { type: 4, index: 68, gl: 128, go: 18 }; // RNM(rep-num)

  /* rep-min-max */
  this.rules[66].opcodes = [];
  this.rules[66].opcodes[0] = { type: 4, index: 68, gl: 129, go: 18 }; // RNM(rep-num)

  /* rep-max */
  this.rules[67].opcodes = [];
  this.rules[67].opcodes[0] = { type: 4, index: 68, gl: 130, go: 18 }; // RNM(rep-num)

  /* rep-num */
  this.rules[68].opcodes = [];
  this.rules[68].opcodes[0] = { type: 3, min: 1, max: Infinity, gl: 131, go: 18 }; // REP
  this.rules[68].opcodes[1] = { type: 5, min: 48, max: 57, gl: 131, go: 21 }; // TRG

  /* dString */
  this.rules[69].opcodes = [];
  this.rules[69].opcodes[0] = { type: 4, index: 81, gl: 132, go: 18 }; // RNM(dnum)

  /* xString */
  this.rules[70].opcodes = [];
  this.rules[70].opcodes[0] = { type: 4, index: 83, gl: 133, go: 18 }; // RNM(xnum)

  /* bString */
  this.rules[71].opcodes = [];
  this.rules[71].opcodes[0] = { type: 4, index: 82, gl: 134, go: 18 }; // RNM(bnum)

  /* Dec */
  this.rules[72].opcodes = [];
  this.rules[72].opcodes[0] = { type: 1, children: [1, 2], gl: 135, go: 19 }; // ALT
  this.rules[72].opcodes[1] = { type: 6, string: [68], gl: 135, go: 19 }; // TBS
  this.rules[72].opcodes[2] = { type: 6, string: [100], gl: 135, go: 24 }; // TBS

  /* Hex */
  this.rules[73].opcodes = [];
  this.rules[73].opcodes[0] = { type: 1, children: [1, 2], gl: 136, go: 19 }; // ALT
  this.rules[73].opcodes[1] = { type: 6, string: [88], gl: 136, go: 19 }; // TBS
  this.rules[73].opcodes[2] = { type: 6, string: [120], gl: 136, go: 24 }; // TBS

  /* Bin */
  this.rules[74].opcodes = [];
  this.rules[74].opcodes[0] = { type: 1, children: [1, 2], gl: 137, go: 19 }; // ALT
  this.rules[74].opcodes[1] = { type: 6, string: [66], gl: 137, go: 19 }; // TBS
  this.rules[74].opcodes[2] = { type: 6, string: [98], gl: 137, go: 24 }; // TBS

  /* dmin */
  this.rules[75].opcodes = [];
  this.rules[75].opcodes[0] = { type: 4, index: 81, gl: 138, go: 18 }; // RNM(dnum)

  /* dmax */
  this.rules[76].opcodes = [];
  this.rules[76].opcodes[0] = { type: 4, index: 81, gl: 139, go: 18 }; // RNM(dnum)

  /* bmin */
  this.rules[77].opcodes = [];
  this.rules[77].opcodes[0] = { type: 4, index: 82, gl: 140, go: 18 }; // RNM(bnum)

  /* bmax */
  this.rules[78].opcodes = [];
  this.rules[78].opcodes[0] = { type: 4, index: 82, gl: 141, go: 18 }; // RNM(bnum)

  /* xmin */
  this.rules[79].opcodes = [];
  this.rules[79].opcodes[0] = { type: 4, index: 83, gl: 142, go: 18 }; // RNM(xnum)

  /* xmax */
  this.rules[80].opcodes = [];
  this.rules[80].opcodes[0] = { type: 4, index: 83, gl: 143, go: 18 }; // RNM(xnum)

  /* dnum */
  this.rules[81].opcodes = [];
  this.rules[81].opcodes[0] = { type: 3, min: 1, max: Infinity, gl: 144, go: 18 }; // REP
  this.rules[81].opcodes[1] = { type: 5, min: 48, max: 57, gl: 144, go: 21 }; // TRG

  /* bnum */
  this.rules[82].opcodes = [];
  this.rules[82].opcodes[0] = { type: 3, min: 1, max: Infinity, gl: 145, go: 18 }; // REP
  this.rules[82].opcodes[1] = { type: 5, min: 48, max: 49, gl: 145, go: 20 }; // TRG

  /* xnum */
  this.rules[83].opcodes = [];
  this.rules[83].opcodes[0] = { type: 3, min: 1, max: Infinity, gl: 146, go: 18 }; // REP
  this.rules[83].opcodes[1] = { type: 1, children: [2, 3, 4], gl: 146, go: 21 }; // ALT
  this.rules[83].opcodes[2] = { type: 5, min: 48, max: 57, gl: 146, go: 21 }; // TRG
  this.rules[83].opcodes[3] = { type: 5, min: 65, max: 70, gl: 146, go: 31 }; // TRG
  this.rules[83].opcodes[4] = { type: 5, min: 97, max: 102, gl: 146, go: 41 }; // TRG

  /* alphanum */
  this.rules[84].opcodes = [];
  this.rules[84].opcodes[0] = { type: 2, children: [1, 4], gl: 149, go: 18 }; // CAT
  this.rules[84].opcodes[1] = { type: 1, children: [2, 3], gl: 149, go: 19 }; // ALT
  this.rules[84].opcodes[2] = { type: 5, min: 97, max: 122, gl: 149, go: 19 }; // TRG
  this.rules[84].opcodes[3] = { type: 5, min: 65, max: 90, gl: 149, go: 28 }; // TRG
  this.rules[84].opcodes[4] = { type: 3, min: 0, max: Infinity, gl: 149, go: 37 }; // REP
  this.rules[84].opcodes[5] = { type: 1, children: [6, 7, 8, 9], gl: 149, go: 39 }; // ALT
  this.rules[84].opcodes[6] = { type: 5, min: 97, max: 122, gl: 149, go: 39 }; // TRG
  this.rules[84].opcodes[7] = { type: 5, min: 65, max: 90, gl: 149, go: 48 }; // TRG
  this.rules[84].opcodes[8] = { type: 5, min: 48, max: 57, gl: 149, go: 56 }; // TRG
  this.rules[84].opcodes[9] = { type: 6, string: [45], gl: 149, go: 64 }; // TBS

  /* owsp */
  this.rules[85].opcodes = [];
  this.rules[85].opcodes[0] = { type: 3, min: 0, max: Infinity, gl: 150, go: 18 }; // REP
  this.rules[85].opcodes[1] = { type: 4, index: 87, gl: 150, go: 19 }; // RNM(space)

  /* wsp */
  this.rules[86].opcodes = [];
  this.rules[86].opcodes[0] = { type: 3, min: 1, max: Infinity, gl: 151, go: 18 }; // REP
  this.rules[86].opcodes[1] = { type: 4, index: 87, gl: 151, go: 20 }; // RNM(space)

  /* space */
  this.rules[87].opcodes = [];
  this.rules[87].opcodes[0] = { type: 1, children: [1, 2, 3, 4], gl: 152, go: 18 }; // ALT
  this.rules[87].opcodes[1] = { type: 6, string: [32], gl: 152, go: 18 }; // TBS
  this.rules[87].opcodes[2] = { type: 6, string: [9], gl: 153, go: 18 }; // TBS
  this.rules[87].opcodes[3] = { type: 4, index: 88, gl: 154, go: 18 }; // RNM(comment)
  this.rules[87].opcodes[4] = { type: 4, index: 90, gl: 155, go: 18 }; // RNM(LineContinue)

  /* comment */
  this.rules[88].opcodes = [];
  this.rules[88].opcodes[0] = { type: 2, children: [1, 2], gl: 156, go: 18 }; // CAT
  this.rules[88].opcodes[1] = { type: 6, string: [59], gl: 156, go: 18 }; // TBS
  this.rules[88].opcodes[2] = { type: 3, min: 0, max: Infinity, gl: 156, go: 23 }; // REP
  this.rules[88].opcodes[3] = { type: 1, children: [4, 5], gl: 156, go: 25 }; // ALT
  this.rules[88].opcodes[4] = { type: 5, min: 32, max: 126, gl: 156, go: 25 }; // TRG
  this.rules[88].opcodes[5] = { type: 6, string: [9], gl: 156, go: 36 }; // TBS

  /* LineEnd */
  this.rules[89].opcodes = [];
  this.rules[89].opcodes[0] = { type: 1, children: [1, 2, 3], gl: 157, go: 18 }; // ALT
  this.rules[89].opcodes[1] = { type: 6, string: [13, 10], gl: 157, go: 18 }; // TBS
  this.rules[89].opcodes[2] = { type: 6, string: [10], gl: 158, go: 18 }; // TBS
  this.rules[89].opcodes[3] = { type: 6, string: [13], gl: 159, go: 18 }; // TBS

  /* LineContinue */
  this.rules[90].opcodes = [];
  this.rules[90].opcodes[0] = { type: 2, children: [1, 5], gl: 160, go: 18 }; // CAT
  this.rules[90].opcodes[1] = { type: 1, children: [2, 3, 4], gl: 160, go: 19 }; // ALT
  this.rules[90].opcodes[2] = { type: 6, string: [13, 10], gl: 160, go: 19 }; // TBS
  this.rules[90].opcodes[3] = { type: 6, string: [10], gl: 160, go: 29 }; // TBS
  this.rules[90].opcodes[4] = { type: 6, string: [13], gl: 160, go: 36 }; // TBS
  this.rules[90].opcodes[5] = { type: 1, children: [6, 7], gl: 160, go: 43 }; // ALT
  this.rules[90].opcodes[6] = { type: 6, string: [32], gl: 160, go: 43 }; // TBS
  this.rules[90].opcodes[7] = { type: 6, string: [9], gl: 160, go: 50 }; // TBS

  // The `toString()` function will display the original grammar file(s) that produced these opcodes.
  this.toString = function toString() {
    let str = '';
    str += ';\n';
    str += '; ABNF for JavaScript APG 2.0 SABNF\n';
    str += '; RFC 5234 with some restrictions and additions.\n';
    str += '; Updated 11/24/2015 for RFC 7405 case-sensitive literal string notation\n';
    str += ';  - accepts %s"string" as a case-sensitive string\n';
    str += ';  - accepts %i"string" as a case-insensitive string\n';
    str += ';  - accepts "string" as a case-insensitive string\n';
    str += ';\n';
    str += '; Some restrictions:\n';
    str += ';   1. Rules must begin at first character of each line.\n';
    str += ';      Indentations on first rule and rules thereafter are not allowed.\n';
    str += ';   2. Relaxed line endings. CRLF, LF or CR are accepted as valid line ending.\n';
    str += ';   3. Prose values, i.e. <prose value>, are accepted as valid grammar syntax.\n';
    str += ';      However, a working parser cannot be generated from them.\n';
    str += ';\n';
    str += '; Super set (SABNF) additions:\n';
    str += ';   1. Look-ahead (syntactic predicate) operators are accepted as element prefixes.\n';
    str += ';      & is the positive look-ahead operator, succeeds and backtracks if the look-ahead phrase is found\n';
    str +=
      ';      ! is the negative look-ahead operator, succeeds and backtracks if the look-ahead phrase is NOT found\n';
    str += ';      e.g. &%d13 or &rule or !(A / B)\n';
    str += ';   2. User-Defined Terminals (UDT) of the form, u_name and e_name are accepted.\n';
    str += ";      'name' is alpha followed by alpha/num/hyphen just like a rule name.\n";
    str += ';      u_name may be used as an element but no rule definition is given.\n';
    str += ';      e.g. rule = A / u_myUdt\n';
    str += ';           A = "a"\n';
    str += ';      would be a valid grammar.\n';
    str += ';   3. Case-sensitive, single-quoted strings are accepted.\n';
    str += ";      e.g. 'abc' would be equivalent to %d97.98.99\n";
    str += ';      (kept for backward compatibility, but superseded by %s"abc")  \n';
    str += '; New 12/26/2015\n';
    str += ';   4. Look-behind operators are accepted as element prefixes.\n';
    str +=
      ';      && is the positive look-behind operator, succeeds and backtracks if the look-behind phrase is found\n';
    str +=
      ';      !! is the negative look-behind operator, succeeds and backtracks if the look-behind phrase is NOT found\n';
    str += ';      e.g. &&%d13 or &&rule or !!(A / B)\n';
    str += ';   5. Back reference operators, i.e. \\rulename, are accepted.\n';
    str += ';      A back reference operator acts like a TLS or TBS terminal except that the phrase it attempts\n';
    str += ";      to match is a phrase previously matched by the rule 'rulename'.\n";
    str += ';      There are two modes of previous phrase matching - the parent-frame mode and the universal mode.\n';
    str +=
      ";      In universal mode, \\rulename matches the last match to 'rulename' regardless of where it was found.\n";
    str +=
      ";      In parent-frame mode, \\rulename matches only the last match found on the parent's frame or parse tree level.\n";
    str += ';      Back reference modifiers can be used to specify case and mode.\n';
    str += ';      \\A defaults to case-insensitive and universal mode, e.g. \\A === \\%i%uA\n';
    str += ';      Modifiers %i and %s determine case-insensitive and case-sensitive mode, respectively.\n';
    str += ';      Modifiers %u and %p determine universal mode and parent frame mode, respectively.\n';
    str += ';      Case and mode modifiers can appear in any order, e.g. \\%s%pA === \\%p%sA. \n';
    str += ';   7. String begin anchor, ABG(%^) matches the beginning of the input string location.\n';
    str += ';      Returns EMPTY or NOMATCH. Never consumes any characters.\n';
    str += ';   8. String end anchor, AEN(%$) matches the end of the input string location.\n';
    str += ';      Returns EMPTY or NOMATCH. Never consumes any characters.\n';
    str += ';\n';
    str += 'File            = *(BlankLine / Rule / RuleError)\n';
    str += 'BlankLine       = *(%d32/%d9) [comment] LineEnd\n';
    str += 'Rule            = RuleLookup owsp Alternation ((owsp LineEnd)\n';
    str += '                / (LineEndError LineEnd))\n';
    str += 'RuleLookup      = RuleNameTest owsp DefinedAsTest\n';
    str += 'RuleNameTest    = RuleName/RuleNameError\n';
    str += 'RuleName        = alphanum\n';
    str += 'RuleNameError   = 1*(%d33-60/%d62-126)\n';
    str += 'DefinedAsTest   = DefinedAs / DefinedAsError\n';
    str += 'DefinedAsError  = 1*2%d33-126\n';
    str += 'DefinedAs       = IncAlt / Defined\n';
    str += 'Defined         = %d61\n';
    str += 'IncAlt          = %d61.47\n';
    str += 'RuleError       = 1*(%d32-126 / %d9  / LineContinue) LineEnd\n';
    str += 'LineEndError    = 1*(%d32-126 / %d9  / LineContinue)\n';
    str += 'Alternation     = Concatenation *(owsp AltOp Concatenation)\n';
    str += 'Concatenation   = Repetition *(CatOp Repetition)\n';
    str += 'Repetition      = [Modifier] (Group / Option / BasicElement / BasicElementErr)\n';
    str += 'Modifier        = (Predicate [RepOp])\n';
    str += '                / RepOp\n';
    str += 'Predicate       = AndOp / NotOp\n';
    str += 'BasicElement    = UdtOp\n';
    str += '                / RnmOp\n';
    str += '                / TrgOp\n';
    str += '                / TbsOp\n';
    str += '                / TlsOp\n';
    str += '                / ClsOp\n';
    str += '                / ProsVal\n';
    str += 'BasicElementErr = 1*(%d33-40/%d42-46/%d48-92/%d94-126)\n';
    str += 'Group           = GroupOpen  Alternation (GroupClose / GroupError)\n';
    str += 'GroupError      = 1*(%d33-40/%d42-46/%d48-92/%d94-126) ; same as BasicElementErr\n';
    str += 'GroupOpen       = %d40 owsp\n';
    str += 'GroupClose      = owsp %d41\n';
    str += 'Option          = OptionOpen Alternation (OptionClose / OptionError)\n';
    str += 'OptionError     = 1*(%d33-40/%d42-46/%d48-92/%d94-126) ; same as BasicElementErr\n';
    str += 'OptionOpen      = %d91 owsp\n';
    str += 'OptionClose     = owsp %d93\n';
    str += 'RnmOp           = alphanum\n';
    str += 'BkrOp           = %d92 [bkrModifier] bkr-name\n';
    str += 'bkrModifier     = (cs [um / pm]) / (ci [um / pm]) / (um [cs /ci]) / (pm [cs / ci])\n';
    str += "cs              = '%s'\n";
    str += "ci              = '%i'\n";
    str += "um              = '%u'\n";
    str += "pm              = '%p'\n";
    str += 'bkr-name        = uname / ename / rname\n';
    str += 'rname           = alphanum\n';
    str += 'uname           = %d117.95 alphanum\n';
    str += 'ename           = %d101.95 alphanum\n';
    str += 'UdtOp           = udt-empty\n';
    str += '                / udt-non-empty\n';
    str += 'udt-non-empty   = %d117.95 alphanum\n';
    str += 'udt-empty       = %d101.95 alphanum\n';
    str += 'RepOp           = (rep-min StarOp rep-max)\n';
    str += '                / (rep-min StarOp)\n';
    str += '                / (StarOp rep-max)\n';
    str += '                / StarOp\n';
    str += '                / rep-min-max\n';
    str += 'AltOp           = %d47 owsp\n';
    str += 'CatOp           = wsp\n';
    str += 'StarOp          = %d42\n';
    str += 'AndOp           = %d38\n';
    str += 'NotOp           = %d33\n';
    str += 'TrgOp           = %d37 ((Dec dmin %d45 dmax) / (Hex xmin %d45 xmax) / (Bin bmin %d45 bmax))\n';
    str +=
      'TbsOp           = %d37 ((Dec dString *(%d46 dString)) / (Hex xString *(%d46 xString)) / (Bin bString *(%d46 bString)))\n';
    str += 'TlsOp           = TlsCase TlsOpen TlsString TlsClose\n';
    str += 'TlsCase         = ["%i" / "%s"]\n';
    str += 'TlsOpen         = %d34\n';
    str += 'TlsClose        = %d34\n';
    str += 'TlsString       = *(%d32-33/%d35-126/StringTab)\n';
    str += 'StringTab       = %d9\n';
    str += 'ClsOp           = ClsOpen ClsString ClsClose\n';
    str += 'ClsOpen         = %d39\n';
    str += 'ClsClose        = %d39\n';
    str += 'ClsString       = *(%d32-38/%d40-126/StringTab)\n';
    str += 'ProsVal         = ProsValOpen ProsValString ProsValClose\n';
    str += 'ProsValOpen     = %d60\n';
    str += 'ProsValString   = *(%d32-61/%d63-126/StringTab)\n';
    str += 'ProsValClose    = %d62\n';
    str += 'rep-min         = rep-num\n';
    str += 'rep-min-max     = rep-num\n';
    str += 'rep-max         = rep-num\n';
    str += 'rep-num         = 1*(%d48-57)\n';
    str += 'dString         = dnum\n';
    str += 'xString         = xnum\n';
    str += 'bString         = bnum\n';
    str += 'Dec             = (%d68/%d100)\n';
    str += 'Hex             = (%d88/%d120)\n';
    str += 'Bin             = (%d66/%d98)\n';
    str += 'dmin            = dnum\n';
    str += 'dmax            = dnum\n';
    str += 'bmin            = bnum\n';
    str += 'bmax            = bnum\n';
    str += 'xmin            = xnum\n';
    str += 'xmax            = xnum\n';
    str += 'dnum            = 1*(%d48-57)\n';
    str += 'bnum            = 1*%d48-49\n';
    str += 'xnum            = 1*(%d48-57 / %d65-70 / %d97-102)\n';
    str += ';\n';
    str += '; Basics\n';
    str += 'alphanum        = (%d97-122/%d65-90) *(%d97-122/%d65-90/%d48-57/%d45)\n';
    str += 'owsp            = *space\n';
    str += 'wsp             = 1*space\n';
    str += 'space           = %d32\n';
    str += '                / %d9\n';
    str += '                / comment\n';
    str += '                / LineContinue\n';
    str += 'comment         = %d59 *(%d32-126 / %d9)\n';
    str += 'LineEnd         = %d13.10\n';
    str += '                / %d10\n';
    str += '                / %d13\n';
    str += 'LineContinue    = (%d13.10 / %d10 / %d13) (%d32 / %d9)\n';
    return str;
  };
}
