// copyright: Copyright (c) 2026 Lowell D. Thomas
//   license: MIT (https://opensource.org/license/MIT)
//
// Generated by apg-esm, Version 1.0.0
export default function grammar() {
  // ```
  // SUMMARY
  //      rules = 10
  //       udts = 0
  //    opcodes = 31
  //        ---   ABNF original opcodes
  //        ALT = 5
  //        CAT = 2
  //        REP = 4
  //        RNM = 11
  //        TLS = 0
  //        TBS = 4
  //        TRG = 5
  //        ---   SABNF superset opcodes
  //        UDT = 0
  //        AND = 0
  //        NOT = 0
  // characters = [0 - 4294967295]
  // ```
  /* OBJECT IDENTIFIER (magic number for internal parser use) */
  this.grammarObject = 'grammarObject';

  /* RULES */
  this.rules = [];
  this.rules[0] = { name: 'file', lower: 'file', index: 0 };
  this.rules[1] = { name: 'line', lower: 'line', index: 1 };
  this.rules[2] = { name: 'line-text', lower: 'line-text', index: 2 };
  this.rules[3] = { name: 'last-line', lower: 'last-line', index: 3 };
  this.rules[4] = { name: 'valid', lower: 'valid', index: 4 };
  this.rules[5] = { name: 'invalid', lower: 'invalid', index: 5 };
  this.rules[6] = { name: 'end', lower: 'end', index: 6 };
  this.rules[7] = { name: 'CRLF', lower: 'crlf', index: 7 };
  this.rules[8] = { name: 'LF', lower: 'lf', index: 8 };
  this.rules[9] = { name: 'CR', lower: 'cr', index: 9 };

  /* UDTS */
  this.udts = [];

  /* OPCODES */
  /* file */
  this.rules[0].opcodes = [];
  this.rules[0].opcodes[0] = { type: 2, children: [1, 3], gl: 0, go: 7 }; // CAT
  this.rules[0].opcodes[1] = { type: 3, min: 0, max: Infinity, gl: 0, go: 7 }; // REP
  this.rules[0].opcodes[2] = { type: 4, index: 1, gl: 0, go: 8 }; // RNM(line)
  this.rules[0].opcodes[3] = { type: 3, min: 0, max: 1, gl: 0, go: 13 }; // REP
  this.rules[0].opcodes[4] = { type: 4, index: 3, gl: 0, go: 14 }; // RNM(last-line)

  /* line */
  this.rules[1].opcodes = [];
  this.rules[1].opcodes[0] = { type: 2, children: [1, 2], gl: 1, go: 7 }; // CAT
  this.rules[1].opcodes[1] = { type: 4, index: 2, gl: 1, go: 7 }; // RNM(line-text)
  this.rules[1].opcodes[2] = { type: 4, index: 6, gl: 1, go: 17 }; // RNM(end)

  /* line-text */
  this.rules[2].opcodes = [];
  this.rules[2].opcodes[0] = { type: 3, min: 0, max: Infinity, gl: 2, go: 12 }; // REP
  this.rules[2].opcodes[1] = { type: 1, children: [2, 3], gl: 2, go: 14 }; // ALT
  this.rules[2].opcodes[2] = { type: 4, index: 4, gl: 2, go: 14 }; // RNM(valid)
  this.rules[2].opcodes[3] = { type: 4, index: 5, gl: 2, go: 20 }; // RNM(invalid)

  /* last-line */
  this.rules[3].opcodes = [];
  this.rules[3].opcodes[0] = { type: 3, min: 1, max: Infinity, gl: 3, go: 12 }; // REP
  this.rules[3].opcodes[1] = { type: 1, children: [2, 3], gl: 3, go: 15 }; // ALT
  this.rules[3].opcodes[2] = { type: 4, index: 4, gl: 3, go: 15 }; // RNM(valid)
  this.rules[3].opcodes[3] = { type: 4, index: 5, gl: 3, go: 21 }; // RNM(invalid)

  /* valid */
  this.rules[4].opcodes = [];
  this.rules[4].opcodes[0] = { type: 1, children: [1, 2], gl: 4, go: 8 }; // ALT
  this.rules[4].opcodes[1] = { type: 5, min: 32, max: 126, gl: 4, go: 8 }; // TRG
  this.rules[4].opcodes[2] = { type: 6, string: [9], gl: 4, go: 19 }; // TBS

  /* invalid */
  this.rules[5].opcodes = [];
  this.rules[5].opcodes[0] = { type: 1, children: [1, 2, 3, 4], gl: 5, go: 10 }; // ALT
  this.rules[5].opcodes[1] = { type: 5, min: 0, max: 8, gl: 5, go: 10 }; // TRG
  this.rules[5].opcodes[2] = { type: 5, min: 11, max: 12, gl: 5, go: 18 }; // TRG
  this.rules[5].opcodes[3] = { type: 5, min: 14, max: 31, gl: 5, go: 27 }; // TRG
  this.rules[5].opcodes[4] = { type: 5, min: 127, max: 4294967295, gl: 5, go: 37 }; // TRG

  /* end */
  this.rules[6].opcodes = [];
  this.rules[6].opcodes[0] = { type: 1, children: [1, 2, 3], gl: 6, go: 6 }; // ALT
  this.rules[6].opcodes[1] = { type: 4, index: 7, gl: 6, go: 6 }; // RNM(CRLF)
  this.rules[6].opcodes[2] = { type: 4, index: 8, gl: 6, go: 13 }; // RNM(LF)
  this.rules[6].opcodes[3] = { type: 4, index: 9, gl: 6, go: 18 }; // RNM(CR)

  /* CRLF */
  this.rules[7].opcodes = [];
  this.rules[7].opcodes[0] = { type: 6, string: [13, 10], gl: 7, go: 7 }; // TBS

  /* LF */
  this.rules[8].opcodes = [];
  this.rules[8].opcodes[0] = { type: 6, string: [10], gl: 8, go: 5 }; // TBS

  /* CR */
  this.rules[9].opcodes = [];
  this.rules[9].opcodes[0] = { type: 6, string: [13], gl: 9, go: 5 }; // TBS

  // The `toString()` function will display the original grammar file(s) that produced these opcodes.
  this.toString = function toString() {
    let str = '';
    str += 'file = *line [last-line]\n';
    str += 'line = line-text end\n';
    str += 'line-text = *(valid/invalid)\n';
    str += 'last-line = 1*(valid/invalid)\n';
    str += 'valid = %d32-126 / %d9\n';
    str += 'invalid = %d0-8 / %d11-12 /%d14-31 / %x7f-ffffffff\n';
    str += 'end = CRLF / LF / CR\n';
    str += 'CRLF = %d13.10\n';
    str += 'LF = %d10\n';
    str += 'CR = %d13\n';
    return str;
  };
}
